### ISSUE TITLE
Make sockdrive tests optional

### ISSUE THREAD

**Issue by citee520** [caiiiycuk/sockdrive#3]
I have the same issue when running test.js. It mentions sockdrive. I tried running it on my local browser, but I still encountered errors.
PS. To run a Python HTTP server locally
<img width="924" alt="sockdrive_error" src="https://github.com/caiiiycuk/sockdrive/assets/6230413/f88a5b28-d36f-4f0c-af7e-5ef5d6e8c44c">
<img width="924" alt="sockdrive_error" src="https://github.com/caiiiycuk/sockdrive/assets/6230413/f88a5b28-d36f-4f0c-af7e-5ef5d6e8c44c">
<img width="924" alt="sockdrive_error" src="https://github.com/caiiiycuk/sockdrive/assets/6230413/f88a5b28-d36f-4f0c-af7e-5ef5d6e8c44c">

**Comment by caiiiycuk** [comment]
This is okay, you need to run sockdrive server locally. This is possible but not yet documented, please ignore Drive * tests for now.
I need to make this test optional

**Comment by citee520** [comment]
Okay, I understand now. Thank you very much for your prompt response.

**Comment by guozanhua218** [comment]
> This is okay, you need to run sockdrive server locally. This is possible but not yet documented, please ignore Drive * tests for now. I need to make this test optional

Hi alex, Could you explain how to convert img file into blob and meta file?

**Comment by caiiiycuk** [comment]
> > This is okay, you need to run sockdrive server locally. This is possible but not yet documented, please ignore Drive * tests for now. I need to make this test optional
> 
> Hi alex, Could you explain how to convert img file into blob and meta file?

What is blob and meta?

**Comment by guozanhua218** [comment]
> > > This is okay, you need to run sockdrive server locally. This is possible but not yet documented, please ignore Drive * tests for now. I need to make this test optional
> > 
> > 
> > Hi alex, Could you explain how to convert img file into blob and meta file?
> 
> What is blob and meta?

Sockdrive backend's drive layer created blob and meta file? Could these files should convert from img file?

**Comment by caiiiycuk** [comment]
> > > > This is okay, you need to run sockdrive server locally. This is possible but not yet documented, please ignore Drive * tests for now. I need to make this test optional
> > > 
> > > 
> > > Hi alex, Could you explain how to convert img file into blob and meta file?
> > 
> > 
> > What is blob and meta?
> 
> Sockdrive backend's drive layer created blob and meta file? Could these files should convert from img file?

I am curios, where you get this info. That sockdrive drive have a blob and meta file???

**Comment by citee520** [comment]
to me, SockDrive establishes a remote WebSocket connection and, upon success, forks to remotely mount a folder or image. I am curious about how SockDrive achieves remote mounting. Is my understanding correct?

**Comment by guozanhua218** [comment]
> > > > > This is okay, you need to run sockdrive server locally. This is possible but not yet documented, please ignore Drive * tests for now. I need to make this test optional
> > > > 
> > > > 
> > > > Hi alex, Could you explain how to convert img file into blob and meta file?
> > > 
> > > 
> > > What is blob and meta?
> > 
> > 
> > Sockdrive backend's drive layer created blob and meta file? Could these files should convert from img file?
> 
> I am curios, where you get this info. That sockdrive drive have a blob and meta file???

I reviewed the _node_module branch, there is a backend test implement by rust lang,which implement a disk layer,but alway create a new drive, So this drive is filled by zero, it hasn't any boot sector information, it start to serve 8002 port for tcp services, which can use websocket proxy service  to convert tcp socket protocol to web socket protocol via 8001, sockdrive can connect with 8001,and can read  correct from drive-0 via sockdrive,but there is no boot sector information,this will result the frontend code result a boot sector validate exception, So I think if  allow the layer can read the correct sector information , the sockdrive frontend test will passed, Is it right?

**Comment by caiiiycuk** [comment]
> > > > > > This is okay, you need to run sockdrive server locally. This is possible but not yet documented, please ignore Drive * tests for now. I need to make this test optional
> > > > > 
> > > > > 
> > > > > Hi alex, Could you explain how to convert img file into blob and meta file?
> > > > 
> > > > 
> > > > What is blob and meta?
> > > 
> > > 
> > > Sockdrive backend's drive layer created blob and meta file? Could these files should convert from img file?
> > 
> > 
> > I am curios, where you get this info. That sockdrive drive have a blob and meta file???
> 
> I reviewed the _node_module branch, there is a backend test implement by rust lang,which implement a disk layer,but alway create a new drive, So this drive is filled by zero, it hasn't any boot sector information, it start to serve 8002 port for tcp services, which can use websocket proxy service to convert tcp socket protocol to web socket protocol via 8001, sockdrive can connect with 8001,and can read correct from drive-0 via sockdrive,but there is no boot sector information,this will result the frontend code result a boot sector validate exception, So I think if allow the layer can read the correct sector information , the sockdrive frontend test will passed, Is it right?

Ahh, clear. Nope this is outdated version of sockdrive. Regarding to your question, in theory it's possible to convert img into sockdrive format, but fromat is not stable and not public. I have plan to make server part public, but again not ready yet.

**Comment by caiiiycuk** [comment]
https://js-dos.com/deployment.html#new-deployment
